name: "global-trade-network"

x-type: "hlfv1"
x-loggingLevel: info

description: "The network to be in if you want to stay in the global trade business"

version: 1.0.0

client:

  organization: ff0791646e9d838b08fc0d8a628a7c6f8d8a0a5f

  logging:
    level: info

  peer:
    timeout:
      connection: 10s
      queryResponse: 45s
      executeTxResponse: 120s
  eventService:
    timeout:
      connection: 10s
      registrationResponse: 50s
  orderer:
    timeout:
      connection: 10s
      response: 45s

  cryptoconfig:
    path: /opt/gopath/src/github.com/hyperledger/fabric

  credentialStore:
    path: "/tmp/hfc-kvs"

    cryptoStore:
      path: /tmp/msp

    wallet: wallet-name

  BCCSP:
    security:
     enabled: true
     default:
      provider: "SW"
     hashAlgorithm: "SHA2"
     softVerify: true
     ephemeral: false
     level: 256

channels:
  
  kcoin-channel:
    orderers:
      
      - orderer-5c3781a4078acc48a3a80a004f5d3c7b38101afe-0.orderer-5c3781a4078acc48a3a80a004f5d3c7b38101afe.default.svc.cluster.local
      
    peers:
      
      peer-ff0791646e9d838b08fc0d8a628a7c6f8d8a0a5f-0.peer-ff0791646e9d838b08fc0d8a628a7c6f8d8a0a5f.default.svc.cluster.local:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      
    chaincodes:
      # - testchain:1.0
      - jtokena:1.0.1
  
organizations:
  
  ff0791646e9d838b08fc0d8a628a7c6f8d8a0a5f:
    mspid: ff0791646e9d838b08fc0d8a628a7c6f8d8a0a5fMSP

    cryptoPath:  ${fabricCertificatesPath}/ff0791646e9d838b08fc0d8a628a7c6f8d8a0a5f.peer-ff0791646e9d838b08fc0d8a628a7c6f8d8a0a5f.default.svc.cluster.local/msp
    tlsCryptoKeyPath: ${fabricCertificatesPath}/ff0791646e9d838b08fc0d8a628a7c6f8d8a0a5f.peer-ff0791646e9d838b08fc0d8a628a7c6f8d8a0a5f.default.svc.cluster.local/tls/server.key
    tlsCryptoCertPath: ${fabricCertificatesPath}/ff0791646e9d838b08fc0d8a628a7c6f8d8a0a5f.peer-ff0791646e9d838b08fc0d8a628a7c6f8d8a0a5f.default.svc.cluster.local/tls/server.crt

    peers:
      
      - peer-ff0791646e9d838b08fc0d8a628a7c6f8d8a0a5f-0.peer-ff0791646e9d838b08fc0d8a628a7c6f8d8a0a5f.default.svc.cluster.local
      
    certificateAuthorities:
      - ca-org1

    adminPrivateKey:
      pem: "-----BEGIN PRIVATE KEY----- <etc>"
    signedCert:
      path: "/tmp/somepath/signed-cert.pem"
  
  ordererorg:
      mspID: "5c3781a4078acc48a3a80a004f5d3c7b38101afeMSP"

      cryptoPath: ${fabricCertificatesPath}/5c3781a4078acc48a3a80a004f5d3c7b38101afe.orderer-5c3781a4078acc48a3a80a004f5d3c7b38101afe.default.svc.cluster.local/msp
#orderer eip: 117.78.39.82
orderers:
  
  orderer-5c3781a4078acc48a3a80a004f5d3c7b38101afe-0.orderer-5c3781a4078acc48a3a80a004f5d3c7b38101afe.default.svc.cluster.local:
    url: grpcs://${ordererEIP}:30805

    grpcOptions:
      ssl-target-name-override: orderer-5c3781a4078acc48a3a80a004f5d3c7b38101afe-0.orderer-5c3781a4078acc48a3a80a004f5d3c7b38101afe.default.svc.cluster.local
      grpc-max-send-message-length: 15

    tlsCACerts:
      path: ${fabricCertificatesPath}/5c3781a4078acc48a3a80a004f5d3c7b38101afe.orderer-5c3781a4078acc48a3a80a004f5d3c7b38101afe.default.svc.cluster.local/msp/tlscacerts/tlsca.5c3781a4078acc48a3a80a004f5d3c7b38101afe-cert.pem
  
#peer eip: 117.78.39.82
peers:
  
  peer-ff0791646e9d838b08fc0d8a628a7c6f8d8a0a5f-0.peer-ff0791646e9d838b08fc0d8a628a7c6f8d8a0a5f.default.svc.cluster.local:
    url: grpcs://${peerEIP}:30605

    eventUrl: grpcs://${peerEIP}:30705

    grpcOptions:
      ssl-target-name-override: peer-ff0791646e9d838b08fc0d8a628a7c6f8d8a0a5f-0.peer-ff0791646e9d838b08fc0d8a628a7c6f8d8a0a5f.default.svc.cluster.local
      grpc.http2.keepalive_time: 15

    tlsCACerts:
      path: ${fabricCertificatesPath}/ff0791646e9d838b08fc0d8a628a7c6f8d8a0a5f.peer-ff0791646e9d838b08fc0d8a628a7c6f8d8a0a5f.default.svc.cluster.local/msp/tlscacerts/tlsca.ff0791646e9d838b08fc0d8a628a7c6f8d8a0a5f-cert.pem
  
certificateAuthorities:
  ca-org1:
    url: https://ca_peerOrg1:7054
    httpOptions:
      verify: true
    tlsCACerts:
      path: $GOPATH/src/github.com/hyperledger/fabric-sdk-go/test/api-server/tls/fabricca/certs/ca_root.pem
      client:
       keyfile: $GOPATH/src/github.com/hyperledger/fabric-sdk-go/test/api-server/tls/fabricca/certs/client/client_fabric_client-key.pem
       certfile: $GOPATH/src/github.com/hyperledger/fabric-sdk-go/test/api-server/tls/fabricca/certs/client/client_fabric_client.pem

    registrar:
      enrollId: admin
      enrollSecret: adminpw
    caName: ca-org1